version: "2.3"

services:
  gem: &default
    build: .
    volumes:
      - .:/usr/src/app
      # for purposes of release
      - $HOME/.ssh:/root/.ssh
      - $HOME/.gitconfig:/root/.gitconfig

  # ci:
  #   <<: *default
  #   command: rake
  #   volumes: []
